server:
  port: 8200
eureka:
  instance:
    hostname: peer2
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://sunshb:123456@peer1:8100/eureka,http://sunshb:123456@peer3:8300/eureka
